### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by IceSelkie** [IceSelkie/SpotifySongTagger#1]
Tasks for the 1.0 release:

### Frontend:
- [x] Create a wireframe outline and template HTML/CSS/JS
- [ ] Have a link to the GitHub from the webpage
- [ ] Create a README.MD in the GitHub
- [ ] Adjustable/sortable columns
- [ ] Store tag selection in local storage

### Backend:
- [ ] Notes on setting up server (SHTML/SSI, .htaccess, NodeJS, etc...)
- [x] Authenticate with Spotify OAuth and PKCE
- [ ] Sessioning to keep users logged in
- [ ] Load songs from playlist into view list
- [ ] Tags create and update playlists
- [ ] Play sample of song though connected device (should just be an API call)
